<a href="https://colab.research.google.com/github/HerilPatel/Machine_Learning/blob/main/Day-2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day - 1 Numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.22.4


In [4]:
#Creating  Numpy Array/List

arr_1 = np.array([1,2,3,4,5])
print(arr_1)
print(type(arr_1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#Passing Tuple to Convert into array

tpl = (1,2,3,4)
arr_2 = np.array(tpl)
print(arr_2)
print(type(arr_2))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
#Dimentionality of the Array.

d0 = np.array(1)
d1 = np.array([1,2])
d2 = np.array([[1,2],[3,4]])
d3 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])

print(d0.ndim)
print(d1.ndim)
print(d2.ndim)
print(d3.ndim)

d5 = np.array([1, 2, 3, 4], ndmin=5)
print(d5)


0
1
2
3
[[[[[1 2 3 4]]]]]


In [7]:
#Array Indexing

print(d1[1])   # 1D array
print(d2[1,1])  #2D array
print(d3[0,0,1])   #Access the third element of the second array 

2
4
2


In [8]:
#Slicing arrays

# array[start:end:step] for 1D array

s1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(s1[2:6])
print(s1[1::2]) #step 2 for whole array
print(s1[::-2]) #Nagative Slicing
print()

# array[row range, column range]
s2 = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(s2[1, 4:]) #printing 15 to 20
print(s2[0:2, 2])

[3 4 5 6]
[ 2  4  6  8 10]
[10  8  6  4  2]

[15 16 17 18 19 20]
[ 3 13]


Day - 2 Numpy Continue...

In [9]:
# Datatype in numpy 

a1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(a1.dtype)

a2 = np.array([11,12,13,14,15], dtype='S')
print(a2.dtype)


a3 = np.array([1, 2, 3, 4], dtype='i4')    #Create an array with data type 4 bytes integer:

print(a3)
print(a3.dtype)

# Converting Data Type on Existing Arrays

a2_1 = a2.astype('i')
print(a2_1.dtype)

a4 = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,0.0])
print("Before Converting: ",a4.dtype)
a4_1 = a4.astype('int')
print("After Converting: ",a4_1.dtype)
print(a4)
print(a4_1)
a4_2 = a4.astype('bool')
print(a4_2)



int64
|S2
[1 2 3 4]
int32
int32
Before Converting:  float64
After Converting:  int64
[1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9 0. ]
[1 2 3 4 5 6 7 8 9 0]
[ True  True  True  True  True  True  True  True  True False]


In [10]:
# array Copy vs View

org = np.array([11,22,33,44,55,66])
cp = org.copy()
vw = org.view()
print(org,"\n",cp)

''' Every NumPy array has the attribute base that returns None if the array owns the data.Otherwise, the base  attribute refers to the original object.''' 

print(org.base)
print(cp.base)
print(vw.base)

[11 22 33 44 55 66] 
 [11 22 33 44 55 66]
None
None
[11 22 33 44 55 66]


In [11]:
# Shape of the Array

d0 = np.array(1)
d1 = np.array([1,2])
d2 = np.array([[1,2],[3,4]])
d3 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
d3_1 = np.array(

   [ 
    [[1,1,1],[1,1,1],[1,1,1]],
    [[2,2,2],[2,2,2],[2,2,2]],
    [[3,3,3],[3,3,3],[3,3,3]],
   ]
)

print(d0.shape)
print(d1.shape)
print(d2.shape)
print(d3.shape)
print(d3_1.shape)



()
(2,)
(2, 2)
(3, 1, 3)
(3, 3, 3)


In [12]:
# Reshaping the array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr1 = np.array([11,22,33,44,55,66,77,88,99])
n_a2 = arr1.reshape(3,3)
print(n_a2)
n_a = arr.reshape(4,-1)
print(n_a)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
for i in d3:
  for j in i:
    for k in j:
      print(k)

# Now do instead of above things.
print()
for i in np.nditer(d3):
  print(i)

1
2
3
4
5
6
7
8
9

1
2
3
4
5
6
7
8
9


In [14]:
from numpy.core.multiarray import nditer
#Iterating Array With Different Data Types

a4 = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,0.0])

for i in nditer(a4, flags=['buffered'], op_dtypes=['S']):
  print(i)

b'1.1'
b'2.2'
b'3.3'
b'4.4'
b'5.5'
b'6.6'
b'7.7'
b'8.8'
b'9.9'
b'0.0'


In [31]:
# Array Join

a1 = np.array([[11,22,33], [44,55,66]])
a2 = np.array([[33,22,11], [44,55,66]])

a_total = np.array((a1 + a2))
print(a_total)

print("Horizontal Concatinate: ",np.concatenate((a1,a2)))
print("Vertical Concatinate: ",np.concatenate((a1,a2), axis = 1)) 
print()
print(np.stack((a1,a2)))
print("V: ",np.vstack((a1,a2)))
print("H: ",np.hstack((a1,a2)))
print("\n",np.dstack((a1,a2)))

[[ 44  44  44]
 [ 88 110 132]]
Horizontal Concatinate:  [[11 22 33]
 [44 55 66]
 [33 22 11]
 [44 55 66]]
Vertical Concatinate:  [[11 22 33 33 22 11]
 [44 55 66 44 55 66]]

[[[11 22 33]
  [44 55 66]]

 [[33 22 11]
  [44 55 66]]]
V:  [[11 22 33]
 [44 55 66]
 [33 22 11]
 [44 55 66]]
H:  [[11 22 33 33 22 11]
 [44 55 66 44 55 66]]

 [[[11 33]
  [22 22]
  [33 11]]

 [[44 44]
  [55 55]
  [66 66]]]


In [42]:
# Array Split

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr_1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

print(np.split(arr,5))
print(np.array_split(arr, 6))
print()
print(np.array_split(arr_1,10))
print()
print(np.array_split(arr_1, 2, axis = 1))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9]), array([10])]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]]), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64)]

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]
