<a href="https://colab.research.google.com/github/HerilPatel/Machine_Learning/blob/main/Day_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.22.4


In [5]:
#Creating  Numpy Array/List

arr_1 = np.array([1,2,3,4,5])
print(arr_1)
print(type(arr_1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#Passing Tuple to Convert into array

tpl = (1,2,3,4)
arr_2 = np.array(tpl)
print(arr_2)
print(type(arr_2))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
#Dimentionality of the Array.

d0 = np.array(1)
d1 = np.array([1,2])
d2 = np.array([[1,2],[3,4]])
d3 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])

print(d0.ndim)
print(d1.ndim)
print(d2.ndim)
print(d3.ndim)

d5 = np.array([1, 2, 3, 4], ndmin=5)
print(d5)


0
1
2
3
[[[[[1 2 3 4]]]]]


In [23]:
#Array Indexing

print(d1[1])   # 1D array
print(d2[1,1])  #2D array
print(d3[0,0,1])   #Access the third element of the second array 

2
4
2


In [36]:
#Slicing arrays

# array[start:end:step] for 1D array

s1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(s1[2:6])
print(s1[1::2]) #step 2 for whole array
print(s1[::-2]) #Nagative Slicing
print()

# array[row range, column range]
s2 = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(s2[1, 4:]) #printing 15 to 20
print(s2[0:2, 2])

[3 4 5 6]
[ 2  4  6  8 10]
[10  8  6  4  2]

[15 16 17 18 19 20]
[ 3 13]
